//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageFile
    {
        public int id { get; set; }
        public System.Guid MessageID { get; set; }
        public string FilePath { get; set; }
        public int AttachType { get; set; }
    
        public virtual ChatMessage ChatMessage { get; set; }
    }
}
