//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _24ayar.Web.Utility.PostaGuverciniSmsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://83.66.137.24/PgApiWs", ConfigurationName="PostaGuverciniSmsService.smsserviceSoap")]
    public interface smsserviceSoap {
        
        // CODEGEN: Parameter 'SendDate' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://83.66.137.24/PgApiWs/SmsInsert_1_N", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        _24ayar.Web.Utility.PostaGuverciniSmsService.SmsInsert_1_NResponse SmsInsert_1_N(_24ayar.Web.Utility.PostaGuverciniSmsService.SmsInsert_1_NRequest request);
        
        // CODEGEN: Parameter 'SendDate' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://83.66.137.24/PgApiWs/SmsInsert_N_N", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        _24ayar.Web.Utility.PostaGuverciniSmsService.SmsInsert_N_NResponse SmsInsert_N_N(_24ayar.Web.Utility.PostaGuverciniSmsService.SmsInsert_N_NRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://83.66.137.24/PgApiWs/SmsStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] SmsStatus(string Username, string Password, string[] MessageIDs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://83.66.137.24/PgApiWs/CreditBalance", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int CreditBalance(string Username, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://83.66.137.24/PgApiWs/IdCheck", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string IdCheck(string Username, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://83.66.137.24/PgApiWs/IdCheck2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string IdCheck2(string Username, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://83.66.137.24/PgApiWs/SmsStatus2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] SmsStatus2(string Username, string Password, string[] MessageIDs);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SmsInsert_1_N", WrapperNamespace="http://83.66.137.24/PgApiWs", IsWrapped=true)]
    public partial class SmsInsert_1_NRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://83.66.137.24/PgApiWs", Order=0)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://83.66.137.24/PgApiWs", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://83.66.137.24/PgApiWs", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> SendDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://83.66.137.24/PgApiWs", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ExpireDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://83.66.137.24/PgApiWs", Order=4)]
        public string[] Recepients;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://83.66.137.24/PgApiWs", Order=5)]
        public string Message;
        
        public SmsInsert_1_NRequest() {
        }
        
        public SmsInsert_1_NRequest(string Username, string Password, System.Nullable<System.DateTime> SendDate, System.Nullable<System.DateTime> ExpireDate, string[] Recepients, string Message) {
            this.Username = Username;
            this.Password = Password;
            this.SendDate = SendDate;
            this.ExpireDate = ExpireDate;
            this.Recepients = Recepients;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SmsInsert_1_NResponse", WrapperNamespace="http://83.66.137.24/PgApiWs", IsWrapped=true)]
    public partial class SmsInsert_1_NResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://83.66.137.24/PgApiWs", Order=0)]
        public string[] SmsInsert_1_NResult;
        
        public SmsInsert_1_NResponse() {
        }
        
        public SmsInsert_1_NResponse(string[] SmsInsert_1_NResult) {
            this.SmsInsert_1_NResult = SmsInsert_1_NResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SmsInsert_N_N", WrapperNamespace="http://83.66.137.24/PgApiWs", IsWrapped=true)]
    public partial class SmsInsert_N_NRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://83.66.137.24/PgApiWs", Order=0)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://83.66.137.24/PgApiWs", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://83.66.137.24/PgApiWs", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> SendDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://83.66.137.24/PgApiWs", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ExpireDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://83.66.137.24/PgApiWs", Order=4)]
        public string[] Recepients;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://83.66.137.24/PgApiWs", Order=5)]
        public string[] Messages;
        
        public SmsInsert_N_NRequest() {
        }
        
        public SmsInsert_N_NRequest(string Username, string Password, System.Nullable<System.DateTime> SendDate, System.Nullable<System.DateTime> ExpireDate, string[] Recepients, string[] Messages) {
            this.Username = Username;
            this.Password = Password;
            this.SendDate = SendDate;
            this.ExpireDate = ExpireDate;
            this.Recepients = Recepients;
            this.Messages = Messages;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SmsInsert_N_NResponse", WrapperNamespace="http://83.66.137.24/PgApiWs", IsWrapped=true)]
    public partial class SmsInsert_N_NResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://83.66.137.24/PgApiWs", Order=0)]
        public string[] SmsInsert_N_NResult;
        
        public SmsInsert_N_NResponse() {
        }
        
        public SmsInsert_N_NResponse(string[] SmsInsert_N_NResult) {
            this.SmsInsert_N_NResult = SmsInsert_N_NResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface smsserviceSoapChannel : _24ayar.Web.Utility.PostaGuverciniSmsService.smsserviceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class smsserviceSoapClient : System.ServiceModel.ClientBase<_24ayar.Web.Utility.PostaGuverciniSmsService.smsserviceSoap>, _24ayar.Web.Utility.PostaGuverciniSmsService.smsserviceSoap {
        
        public smsserviceSoapClient() {
        }
        
        public smsserviceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public smsserviceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public smsserviceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public smsserviceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _24ayar.Web.Utility.PostaGuverciniSmsService.SmsInsert_1_NResponse _24ayar.Web.Utility.PostaGuverciniSmsService.smsserviceSoap.SmsInsert_1_N(_24ayar.Web.Utility.PostaGuverciniSmsService.SmsInsert_1_NRequest request) {
            return base.Channel.SmsInsert_1_N(request);
        }
        
        public string[] SmsInsert_1_N(string Username, string Password, System.Nullable<System.DateTime> SendDate, System.Nullable<System.DateTime> ExpireDate, string[] Recepients, string Message) {
            _24ayar.Web.Utility.PostaGuverciniSmsService.SmsInsert_1_NRequest inValue = new _24ayar.Web.Utility.PostaGuverciniSmsService.SmsInsert_1_NRequest();
            inValue.Username = Username;
            inValue.Password = Password;
            inValue.SendDate = SendDate;
            inValue.ExpireDate = ExpireDate;
            inValue.Recepients = Recepients;
            inValue.Message = Message;
            _24ayar.Web.Utility.PostaGuverciniSmsService.SmsInsert_1_NResponse retVal = ((_24ayar.Web.Utility.PostaGuverciniSmsService.smsserviceSoap)(this)).SmsInsert_1_N(inValue);
            return retVal.SmsInsert_1_NResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _24ayar.Web.Utility.PostaGuverciniSmsService.SmsInsert_N_NResponse _24ayar.Web.Utility.PostaGuverciniSmsService.smsserviceSoap.SmsInsert_N_N(_24ayar.Web.Utility.PostaGuverciniSmsService.SmsInsert_N_NRequest request) {
            return base.Channel.SmsInsert_N_N(request);
        }
        
        public string[] SmsInsert_N_N(string Username, string Password, System.Nullable<System.DateTime> SendDate, System.Nullable<System.DateTime> ExpireDate, string[] Recepients, string[] Messages) {
            _24ayar.Web.Utility.PostaGuverciniSmsService.SmsInsert_N_NRequest inValue = new _24ayar.Web.Utility.PostaGuverciniSmsService.SmsInsert_N_NRequest();
            inValue.Username = Username;
            inValue.Password = Password;
            inValue.SendDate = SendDate;
            inValue.ExpireDate = ExpireDate;
            inValue.Recepients = Recepients;
            inValue.Messages = Messages;
            _24ayar.Web.Utility.PostaGuverciniSmsService.SmsInsert_N_NResponse retVal = ((_24ayar.Web.Utility.PostaGuverciniSmsService.smsserviceSoap)(this)).SmsInsert_N_N(inValue);
            return retVal.SmsInsert_N_NResult;
        }
        
        public string[] SmsStatus(string Username, string Password, string[] MessageIDs) {
            return base.Channel.SmsStatus(Username, Password, MessageIDs);
        }
        
        public int CreditBalance(string Username, string Password) {
            return base.Channel.CreditBalance(Username, Password);
        }
        
        public string IdCheck(string Username, string Password) {
            return base.Channel.IdCheck(Username, Password);
        }
        
        public string IdCheck2(string Username, string Password) {
            return base.Channel.IdCheck2(Username, Password);
        }
        
        public string[] SmsStatus2(string Username, string Password, string[] MessageIDs) {
            return base.Channel.SmsStatus2(Username, Password, MessageIDs);
        }
    }
}
